version: '3.8'
services:
  alfashop:
    container_name: "alfashop"
    build: ./
    ports:
      - "8083:8083"
    environment:
    - DATABASE_URL=jdbc:mysql://mysqldb:3306/alfashop
    - DATABASE_USERNAME=root
    - DATABASE_PASSWORD=root
    depends_on:
      - mysqldb
    restart: unless-stopped
  mysqldb:
    container_name: "mysqldb"
    image: "mysql:8"
    ports:
      - "3307:3306"
    environment:
      MYSQL_DATABASE: alfashop
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: root